project:
  type: website
  output-dir: docs

website:
  title: "Dalila Lara"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

